version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:17.3.6-ce.0
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'localhost:82'
        gitlab_rails['gitlab_shell_ssh_port'] = 24
    ports:
      - '82:82'
      - '445:443'
      - '24:24'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'